# Questions Level 1 (Q1-Q20: Foundation) and Level 2 (Q21-Q40: Professional)
from generate_base import make_q

def get_level1_and_level2():
    questions = []

    # Q1: Foundation - Workplace / Time & Priority
    questions.append(make_q(
        1, 1, "Workplace",
        "You receive an urgent request from a peer at 4:30 PM requesting help with an unexpected data format issue, while you have a scheduled task due for your own supervisor tomorrow at 9:00 AM.",
        "How do you address this immediate clash in expectations?",
        [
            ("A", "Quickly review their data issue for 15 minutes to estimate complexity, then either offer a quick fix or schedule morning support.", {"time_priority_iq": 90, "teamwork_iq": 85, "problem_solving_iq": 80, "communication_iq": 80}, "moderate", "analytical_triage"),
            ("B", "Immediately set aside your own task and stay late until both your peer's issue and your morning deliverable are fully resolved.", {"teamwork_iq": 85, "time_priority_iq": 50, "job_readiness_iq": 65, "eq": 70}, "high", "overextension"),
            ("C", "Politely explain that your own deadline is locked for 9:00 AM, advising them to escalate to the team lead if they cannot wait.", {"time_priority_iq": 85, "communication_iq": 70, "teamwork_iq": 55, "eq": 60}, "low", "boundary_setting"),
            ("D", "Share a standard documentation guide or previous template that might help them debug it independently this evening.", {"problem_solving_iq": 80, "communication_iq": 75, "time_priority_iq": 85, "teamwork_iq": 70}, "low", "resource_sharing")
        ],
        {"time_priority_iq": 40, "teamwork_iq": 30, "communication_iq": 20, "problem_solving_iq": 10},
        45,
        "Balancing peer solidarity with strict deliverable accountability requires rapid triage rather than automatic over-commitment.",
        "Prioritize clarifying scope and timeline impact before accepting unmanaged spillover work.",
        ["Corporate", "IT", "Consulting", "Finance"]
    ))

    # Q2: Foundation - Internship / Learning Agility
    questions.append(make_q(
        2, 1, "Internship",
        "During your first month as an intern, you notice that a spreadsheet calculation methodology your mentor taught you appears to yield a 4% variance compared to the newly updated company guidelines.",
        "What is your immediate course of action?",
        [
            ("A", "Quietly adjust your sheet to match the new company guideline without bringing it up to avoid questioning your mentor's expertise.", {"ethics_judgment_iq": 60, "communication_iq": 50, "job_readiness_iq": 55, "eq": 60}, "low", "silent_correction"),
            ("B", "Schedule a brief 1-on-1 with your mentor, sharing your side-by-side comparison respectfully to ask for their perspective on the discrepancy.", {"communication_iq": 95, "critical_thinking_iq": 90, "learning_agility_iq": 90, "eq": 85}, "moderate", "respectful_inquiry"),
            ("C", "Raise the issue in the upcoming departmental all-hands meeting so everyone is made aware of the guideline discrepancy.", {"communication_iq": 45, "eq": 40, "leadership_iq": 50, "job_readiness_iq": 45}, "high", "public_escalation"),
            ("D", "Re-run the calculations with historical data sets first to verify whether this variance produces material business impact before speaking up.", {"critical_thinking_iq": 90, "problem_solving_iq": 90, "business_iq": 80, "job_readiness_iq": 85}, "low", "data_verification")
        ],
        {"communication_iq": 35, "critical_thinking_iq": 30, "learning_agility_iq": 20, "eq": 15},
        45,
        "Constructive validation coupled with private, respectful dialogue builds trust while safeguarding analytical rigor.",
        "When finding potential errors in senior guidance, verify the facts calmly and frame the inquiry around clarification.",
        ["Banking", "Education", "Consulting", "Retail"]
    ))

    # Q3: Foundation - AI Situations / AIQ
    questions.append(make_q(
        3, 1, "AI",
        "An AI language model generates an articulate, comprehensive market summary for your project. However, two citations reference market research reports you cannot verify through public search engines.",
        "How do you handle this unverified AI output?",
        [
            ("A", "Include the AI citations directly since the narrative reasoning and numerical projections seem completely credible.", {"aiq": 35, "critical_thinking_iq": 30, "ethics_judgment_iq": 40, "job_readiness_iq": 40}, "high", "blind_trust"),
            ("B", "Remove the unverified citations and cross-check the underlying claims against primary, reputable industry sources before inclusion.", {"aiq": 95, "critical_thinking_iq": 95, "ethics_judgment_iq": 90, "job_readiness_iq": 90}, "low", "rigorous_verification"),
            ("C", "Add a disclaimer at the bottom stating 'Data generated by AI and may contain hallucinated references.'", {"aiq": 65, "job_readiness_iq": 60, "communication_iq": 65, "critical_thinking_iq": 60}, "moderate", "disclaimer_offload"),
            ("D", "Prompt the AI again asking it to re-confirm whether the sources are genuine or synthetic.", {"aiq": 60, "critical_thinking_iq": 60, "problem_solving_iq": 65, "learning_agility_iq": 60}, "moderate", "recursive_prompting")
        ],
        {"aiq": 45, "critical_thinking_iq": 30, "ethics_judgment_iq": 15, "job_readiness_iq": 10},
        40,
        "AI output requires human-in-the-loop verification. Hallucinated citations must never enter professional deliverables.",
        "Always isolate assertions made by AI models and validate against primary, authoritative sources.",
        ["IT", "Marketing", "Consulting", "Education"]
    ))

    # Q4: Foundation - Interview Situations / Interview IQ
    questions.append(make_q(
        4, 1, "Interview",
        "During a final-round job interview, the interviewer asks a technical question about a framework or protocol you have read about briefly but have never actually used in practice.",
        "How do you frame your response?",
        [
            ("A", "Confidently claim you used it during a capstone project and attempt to infer answers from general principles.", {"interview_iq": 40, "ethics_judgment_iq": 35, "eq": 40, "communication_iq": 45}, "high", "bluffing"),
            ("B", "State clearly that you have theoretical familiarity but haven't implemented it in production, then explain how your related experience enables rapid adoption.", {"interview_iq": 95, "communication_iq": 90, "learning_agility_iq": 95, "ethics_judgment_iq": 90}, "moderate", "authentic_transfer"),
            ("C", "Simply answer 'I do not know' and remain quiet until the interviewer moves to the next question.", {"interview_iq": 55, "communication_iq": 50, "job_readiness_iq": 50, "learning_agility_iq": 45}, "low", "passive_surrender"),
            ("D", "Pivot immediately to discuss a different tool that you know thoroughly without acknowledging the framework they asked about.", {"interview_iq": 60, "communication_iq": 60, "critical_thinking_iq": 55, "eq": 60}, "moderate", "unacknowledged_deflection")
        ],
        {"interview_iq": 40, "communication_iq": 25, "learning_agility_iq": 20, "ethics_judgment_iq": 15},
        45,
        "Interviewers value authentic self-awareness combined with cognitive flexibility and clear conceptual mapping.",
        "Frame knowledge gaps as active learning bridges by showing how your current skills map to unfamiliar domains.",
        ["All"]
    ))

    # Q5: Foundation - Teamwork / EQ (with Micro-Scenario)
    questions.append(make_q(
        5, 1, "Teamwork",
        "In a student or project team of four, one peer consistently fails to attend sprint check-ins and delivers their assigned slides late, forcing others to format them at midnight.",
        "What is your first step as a proactive teammate?",
        [
            ("A", "Report the individual immediately to the project evaluator or professor to seek a grade penalty.", {"teamwork_iq": 45, "eq": 50, "leadership_iq": 45, "communication_iq": 50}, "high", "early_escalation"),
            ("B", "Initiate a private, non-judgmental conversation to understand if they face unexpected blockers, while clarifying the downstream impact on the team.", {"teamwork_iq": 95, "eq": 95, "communication_iq": 90, "leadership_iq": 85}, "moderate", "empathetic_dialogue"),
            ("C", "Take over their portion entirely to safeguard the team's submission quality without confronting them.", {"teamwork_iq": 60, "eq": 55, "time_priority_iq": 60, "leadership_iq": 50}, "moderate", "martyrdom"),
            ("D", "Call them out in the group chat so peer transparency forces them to honor their commitments.", {"teamwork_iq": 50, "eq": 40, "communication_iq": 50, "leadership_iq": 45}, "high", "public_pressure")
        ],
        {"teamwork_iq": 35, "eq": 30, "communication_iq": 20, "leadership_iq": 15},
        45,
        "Direct empathetic inquiry uncovers hidden friction points before frustration metastasizes into team breakdown.",
        "Address interpersonal accountability privately first; preserve dignity while maintaining project standards.",
        ["Education", "Startups", "Corporate"],
        micro_scenario={
            "triggerOption": "B",
            "complication": "During your private conversation, your peer confides that a family medical crisis has overwhelmed their focus and they feel embarrassed to ask for help.",
            "followUpQuestion": "How do you navigate this newly revealed constraint?",
            "followUpOptions": [
                {"key": "A", "text": "Help redistribute their tasks into smaller modular chunks, agree on specific check-in dates, and inform the team lead on adjusted timelines without exposing private details.", "score": 95, "trait": "empathetic_leader"},
                {"key": "B", "text": "Advise them to drop out of the project immediately so the team's timeline is not jeopardized.", "score": 45, "trait": "rigid_expulsion"},
                {"key": "C", "text": "Offer to do all of their remaining work secretly so no one else finds out.", "score": 60, "trait": "untenable_cover"}
            ]
        }
    ))

    # Q6: Foundation - College / Problem Solving
    questions.append(make_q(
        6, 1, "College",
        "Your final semester capstone project server crashes 18 hours before demonstration day, and the most recent database backup is 48 hours old.",
        "What is your immediate priority?",
        [
            ("A", "Panic and draft an email requesting an extension from the examination committee.", {"problem_solving_iq": 40, "adaptability_iq": 45, "job_readiness_iq": 40, "iq": 45}, "high", "defeatist"),
            ("B", "Isolate the root cause of the crash in logs first, assess data loss delta, and formulate a rollback versus hotfix plan with estimated times.", {"problem_solving_iq": 95, "critical_thinking_iq": 95, "adaptability_iq": 90, "iq": 90}, "moderate", "structured_triage"),
            ("C", "Immediately restore the 48-hour backup without investigating what triggered the crash.", {"problem_solving_iq": 65, "critical_thinking_iq": 55, "risk": "high", "iq": 60}, "high", "premature_reversion"),
            ("D", "Split the team into two: one pair recreates missing data manually while the other rewrites the demo script.", {"problem_solving_iq": 75, "leadership_iq": 80, "time_priority_iq": 70, "adaptability_iq": 75}, "moderate", "parallel_recovery")
        ],
        {"problem_solving_iq": 40, "critical_thinking_iq": 30, "adaptability_iq": 20, "iq": 10},
        45,
        "Systemic crisis requires disciplined triage: understand the failure mode before executing irreversible rollback actions.",
        "Under high time pressure, separate symptom mitigation from root-cause identification.",
        ["IT", "Engineering", "Education"]
    ))

    # Q7: Foundation - Customer / EQ & Communication
    questions.append(make_q(
        7, 1, "Customer",
        "A client reaches out visibly upset because an onboarding training session started 15 minutes late due to an audiovisual connectivity failure on your end.",
        "How do you address the client's frustration?",
        [
            ("A", "Explain in detail that the hotel Wi-Fi was experiencing unprecedented network latency outside your personal control.", {"communication_iq": 50, "eq": 45, "job_readiness_iq": 50, "sales_iq": 45}, "moderate", "defensive_blame"),
            ("B", "Acknowledge the inconvenience sincerely, apologize for the lost time, summarize what was delivered, and offer a dedicated supplementary session.", {"communication_iq": 95, "eq": 95, "sales_iq": 85, "job_readiness_iq": 90}, "low", "empathetic_ownership"),
            ("C", "Offer an immediate 20% refund on the service fee without discussing the underlying concerns.", {"eq": 60, "business_iq": 55, "sales_iq": 60, "job_readiness_iq": 60}, "moderate", "financial_appeasement"),
            ("D", "Remind the client that the contractual agreement permits a grace period for technical setup delays.", {"communication_iq": 40, "eq": 35, "job_readiness_iq": 40, "sales_iq": 40}, "high", "legalistic_rigidity")
        ],
        {"eq": 40, "communication_iq": 35, "job_readiness_iq": 15, "sales_iq": 10},
        45,
        "Customer reassurance requires empathetic ownership of the experience rather than technical rationalization of the failure.",
        "Own the setback, validate their frustration, and proactively offer value-restoring next steps.",
        ["Retail", "Consulting", "Hospitality", "Customer Service"]
    ))

    # Q8: Foundation - Ethics / Ethics & Professional Judgment
    questions.append(make_q(
        8, 1, "Ethical",
        "You accidentally discover a spreadsheet left open on a shared printer containing prospective salary bands and performance ratings for your department peers.",
        "What do you do with this sensitive document?",
        [
            ("A", "Read through it quickly to gauge where your own compensation stands relative to teammates.", {"ethics_judgment_iq": 30, "job_readiness_iq": 35, "eq": 40, "promotion_readiness_iq": 30}, "high", "opportunistic_breach"),
            ("B", "Take a smartphone photo of the document in case management treats you unfairly in future evaluations.", {"ethics_judgment_iq": 25, "job_readiness_iq": 25, "risk": "high", "communication_iq": 30}, "high", "covert_exploitation"),
            ("C", "Secure the document immediately, deliver it directly to the HR manager or document owner, and refrain from browsing or discussing it.", {"ethics_judgment_iq": 98, "job_readiness_iq": 95, "leadership_iq": 90, "promotion_readiness_iq": 85}, "low", "confidentiality_champion"),
            ("D", "Shred the document on the spot so nobody else can read it.", {"ethics_judgment_iq": 70, "job_readiness_iq": 65, "critical_thinking_iq": 60, "problem_solving_iq": 65}, "moderate", "unilateral_destruction")
        ],
        {"ethics_judgment_iq": 50, "job_readiness_iq": 25, "leadership_iq": 15, "promotion_readiness_iq": 10},
        35,
        "Professional integrity is defined by what you do when confidential data is within easy reach and unmonitored.",
        "Respect information boundaries rigorously; safeguard organizational privacy without curiosity breaches.",
        ["All"]
    ))

    # Q9: Foundation - Programming / Computational Logic (Industry-neutral logic)
    questions.append(make_q(
        9, 1, "Programming",
        "A automated process runs fine for standard monthly invoices, but whenever a customer has a credit balance or zero billing amount, the workflow silently stops without generating error alerts.",
        "What diagnostic approach best identifies the structural defect?",
        [
            ("A", "Increase server memory and CPU capacity since processes often hang under heavy calculation loads.", {"programming_iq": 40, "iq": 45, "problem_solving_iq": 45, "critical_thinking_iq": 40}, "moderate", "resource_shotgun"),
            ("B", "Examine conditional branch logic handling boundary values (<= 0) and verify whether unhandled null or negative values terminate the execution pipeline.", {"programming_iq": 95, "iq": 95, "problem_solving_iq": 95, "critical_thinking_iq": 90}, "low", "boundary_inspection"),
            ("C", "Manually delete all zero-balance records from the database before running the script each month.", {"programming_iq": 35, "problem_solving_iq": 40, "job_readiness_iq": 40, "iq": 40}, "high", "crude_workaround"),
            ("D", "Rewrite the entire invoicing pipeline from scratch in a different language.", {"programming_iq": 55, "time_priority_iq": 40, "problem_solving_iq": 50, "business_iq": 45}, "high", "premature_rebuild")
        ],
        {"programming_iq": 45, "problem_solving_iq": 25, "iq": 20, "critical_thinking_iq": 10},
        50,
        "Robust algorithmic reasoning isolates edge-case condition statements (zero, negative, null) before proposing infrastructure changes.",
        "Always test boundary conditions and verify exit paths when silent failures occur.",
        ["IT", "Finance", "Operations"]
    ))

    # Q10: Foundation - Communication / Communication IQ
    questions.append(make_q(
        10, 1, "Communication",
        "You are presenting a quarterly progress update to senior stakeholders who have only 10 minutes of attention before their next board meeting.",
        "How do you organize your presentation delivery?",
        [
            ("A", "Walk through every slide methodically from background methodology to detailed implementation steps, speeding up your speech.", {"communication_iq": 45, "time_priority_iq": 40, "eq": 45, "leadership_iq": 40}, "moderate", "chronological_rush"),
            ("B", "Lead with executive outcomes, critical metrics, and key decisions required, keeping technical appendix slides ready only if asked.", {"communication_iq": 95, "time_priority_iq": 95, "leadership_iq": 90, "business_iq": 90}, "low", "minto_pyramid_executive"),
            ("C", "Skip slides altogether and invite open questions immediately without presenting any baseline context.", {"communication_iq": 65, "eq": 60, "job_readiness_iq": 60, "business_iq": 60}, "moderate", "unstructured_qna"),
            ("D", "Hand them a 15-page printed packet and ask them to email their questions later.", {"communication_iq": 40, "job_readiness_iq": 40, "eq": 45, "business_iq": 40}, "high", "passive_distribution")
        ],
        {"communication_iq": 40, "time_priority_iq": 25, "business_iq": 20, "leadership_iq": 15},
        40,
        "Senior executive communication demands bottom-line first: deliver decisive findings and clear call-to-actions upfront.",
        "Structure high-stakes brevity using top-down synthesis: Headline -> Impact -> Required Decision.",
        ["Corporate", "Consulting", "Finance", "Sales"]
    ))

    # Q11: Foundation - Learning / Learning Agility
    questions.append(make_q(
        11, 1, "Learning",
        "A core software tool or internal system your organization relied on for three years is replaced overnight with a radically different platform.",
        "How do you approach mastering the transition?",
        [
            ("A", "Continue using the deprecated legacy tool through workarounds until the company completely terminates access.", {"learning_agility_iq": 35, "adaptability_iq": 35, "job_readiness_iq": 40, "iq": 40}, "high", "change_resistance"),
            ("B", "Audit your core recurring daily workflows, map them to the new tool's capabilities, review vendor best-practice modules, and document tip sheets for peers.", {"learning_agility_iq": 95, "adaptability_iq": 95, "leadership_iq": 85, "job_readiness_iq": 90}, "low", "systematic_upskilling"),
            ("C", "Wait for the company to organize formal mandatory training sessions before trying any features.", {"learning_agility_iq": 50, "adaptability_iq": 50, "job_readiness_iq": 55, "leadership_iq": 45}, "moderate", "passive_waiting"),
            ("D", "Send feedback complaining that the previous tool had superior UI shortcuts.", {"learning_agility_iq": 40, "communication_iq": 45, "eq": 40, "adaptability_iq": 40}, "moderate", "unconstructive_critique")
        ],
        {"learning_agility_iq": 40, "adaptability_iq": 35, "job_readiness_iq": 15, "leadership_iq": 10},
        45,
        "High learning agility is demonstrated through proactive workflow translation and sharing emerging insights with peers.",
        "Embrace technological shifts as opportunities to modernize your personal workflow architecture.",
        ["All"]
    ))

    # Q12: Foundation - Sales / Sales IQ
    questions.append(make_q(
        12, 1, "Sales",
        "During an initial discovery conversation, a prospective business client says: 'Your competitor offers almost the exact same service at 25% lower pricing.'",
        "What is your most constructive strategic response?",
        [
            ("A", "Match the competitor's 25% discount immediately to secure the deal on the spot.", {"sales_iq": 50, "business_iq": 45, "negotiation_iq": 50, "critical_thinking_iq": 45}, "high", "margin_erosion"),
            ("B", "Acknowledge price importance, then ask clarifying questions about their specific SLA, security, and support requirements to uncover total cost of ownership differences.", {"sales_iq": 95, "business_iq": 90, "communication_iq": 90, "critical_thinking_iq": 85}, "low", "value_differentiation"),
            ("C", "Argue that the competitor's product is unreliable and that cheap providers always deliver inferior quality.", {"sales_iq": 45, "communication_iq": 45, "eq": 40, "job_readiness_iq": 45}, "high", "competitor_bashing"),
            ("D", "State firmly that premium quality commands premium price and refuse further price discussion.", {"sales_iq": 55, "communication_iq": 50, "eq": 50, "business_iq": 55}, "moderate", "rigid_dismissal")
        ],
        {"sales_iq": 45, "business_iq": 25, "communication_iq": 20, "critical_thinking_iq": 10},
        45,
        "Mastery in sales focuses on uncovering the total value equation rather than reacting emotionally to superficial price anchors.",
        "Probe deeper into business outcomes and risk exposure to reframe price comparisons into value comparisons.",
        ["Sales", "Consulting", "Retail", "Startups"]
    ))

    # Q13: Foundation - Marketing / Marketing IQ
    questions.append(make_q(
        13, 1, "Marketing",
        "A social media recruitment campaign generates 100,000 video impressions and high click counts, but only 3 candidates submit actual completed job applications.",
        "What does this data discrepancy most clearly indicate?",
        [
            ("A", "The video content is terrible and should be taken down immediately.", {"marketing_iq": 45, "critical_thinking_iq": 45, "problem_solving_iq": 45, "iq": 50}, "moderate", "premature_conclusion"),
            ("B", "There is a severe conversion funnel friction: the hook attracts attention, but the landing page or application form has excessive friction or misaligned expectations.", {"marketing_iq": 95, "critical_thinking_iq": 95, "problem_solving_iq": 90, "iq": 85}, "low", "funnel_diagnostics"),
            ("C", "Double the advertising budget to push impressions to 200,000 to increase raw application numbers.", {"marketing_iq": 30, "business_iq": 30, "critical_thinking_iq": 35, "problem_solving_iq": 35}, "high", "wasteful_scaling"),
            ("D", "Assume the target audience has zero interest in working at your company.", {"marketing_iq": 40, "critical_thinking_iq": 40, "eq": 45, "business_iq": 40}, "moderate", "fatalistic_generalization")
        ],
        {"marketing_iq": 45, "critical_thinking_iq": 25, "problem_solving_iq": 20, "iq": 10},
        45,
        "Effective marketing analyzes the whole conversion funnel; high top-of-funnel traffic with zero conversions highlights landing page friction.",
        "Always isolate drop-off stages in user journeys before diagnosing the entire campaign as flawed.",
        ["Marketing", "Startups", "Corporate", "HR"]
    ))

    # Q14: Foundation - Critical Thinking / Critical Thinking IQ
    questions.append(make_q(
        14, 1, "Critical Thinking",
        "A colleague presents a chart showing that customer satisfaction scores rose simultaneously in the months after free snacks were added to the breakroom, claiming the snacks boosted client happiness.",
        "What logical error or analytical step should you address first?",
        [
            ("A", "Congratulate them and request buying even more snacks for higher customer ratings.", {"critical_thinking_iq": 35, "iq": 40, "business_iq": 35, "problem_solving_iq": 40}, "moderate", "gullible_agreement"),
            ("B", "Note that correlation does not establish causation, and investigate whether concurrent product releases or seasonal factors drove the satisfaction gain.", {"critical_thinking_iq": 98, "iq": 95, "problem_solving_iq": 90, "business_iq": 85}, "low", "confounding_variable_analysis"),
            ("C", "Publicly ridicule the hypothesis as completely unscientific.", {"critical_thinking_iq": 60, "eq": 30, "communication_iq": 35, "teamwork_iq": 35}, "high", "combative_mockery"),
            ("D", "Conduct a blind taste test of the snacks among clients to prove the correlation.", {"critical_thinking_iq": 50, "problem_solving_iq": 55, "time_priority_iq": 45, "business_iq": 45}, "moderate", "misdirected_experimentation")
        ],
        {"critical_thinking_iq": 45, "iq": 30, "business_iq": 15, "eq": 10},
        40,
        "Critical thinkers systematically disentangle incidental correlation from true causal mechanisms.",
        "Look for lurking variables and external seasonal cycles before accepting convenient causal narratives.",
        ["Finance", "Consulting", "Healthcare", "IT"]
    ))

    # Q15: Foundation - Adaptability / Adaptability IQ
    questions.append(make_q(
        15, 1, "Adaptability",
        "Halfway through a two-week sprint, your team's primary client drastically alters their regulatory requirements, making 40% of your completed work redundant.",
        "How do you personally react and align with the shift?",
        [
            ("A", "Express open frustration during standup and argue against adopting the new regulatory requirements.", {"adaptability_iq": 40, "job_readiness_iq": 45, "eq": 40, "leadership_iq": 40}, "high", "resistance"),
            ("B", "Conduct a rapid salvage audit to identify reusable modular components, archive redundant work neatly, and recalibrate milestone sprint goals.", {"adaptability_iq": 95, "problem_solving_iq": 95, "time_priority_iq": 90, "job_readiness_iq": 90}, "low", "resilient_reorientation"),
            ("C", "Silently discard all past files and restart everything from square one without checking reusable assets.", {"adaptability_iq": 65, "time_priority_iq": 55, "business_iq": 55, "problem_solving_iq": 60}, "moderate", "wasteful_reset"),
            ("D", "Freeze all progress until senior management promises this will be the final change.", {"adaptability_iq": 45, "job_readiness_iq": 45, "communication_iq": 50, "time_priority_iq": 40}, "high", "work_stoppage")
        ],
        {"adaptability_iq": 40, "problem_solving_iq": 25, "time_priority_iq": 20, "job_readiness_iq": 15},
        45,
        "Professional adaptability combines emotional calm with rigorous salvage analysis and rapid scope re-alignment.",
        "Separate the sunk cost from future value; isolate reusable work and pivot toward the new regulatory standard.",
        ["All"]
    ))

    # Q16: Foundation - Leadership / Leadership IQ (with Micro-Scenario)
    questions.append(make_q(
        16, 1, "Leadership",
        "You are coordinating a small volunteer or project sub-committee where two capable members strongly disagree on whether to use a physical showcase or a digital portal for the annual showcase.",
        "How do you facilitate alignment?",
        [
            ("A", "Make an executive decision immediately based on your personal preference to avoid debating.", {"leadership_iq": 55, "eq": 50, "teamwork_iq": 50, "communication_iq": 55}, "moderate", "autocratic_cutoff"),
            ("B", "Frame the decision around objective evaluation criteria (budget, attendee profile, timeline, reach) and invite both members to score both options against these metrics.", {"leadership_iq": 95, "communication_iq": 90, "critical_thinking_iq": 90, "eq": 85}, "low", "objective_criteria_alignment"),
            ("C", "Let them debate endlessly until one of them concedes from exhaustion.", {"leadership_iq": 35, "time_priority_iq": 30, "eq": 40, "teamwork_iq": 35}, "high", "abdication"),
            ("D", "Split the committee into two rival groups and produce both simultaneously.", {"leadership_iq": 50, "time_priority_iq": 45, "business_iq": 40, "teamwork_iq": 50}, "high", "resource_duplication")
        ],
        {"leadership_iq": 40, "communication_iq": 25, "eq": 20, "critical_thinking_iq": 15},
        45,
        "Authentic leadership resolves interpersonal conflict by replacing subjective opinions with agreed objective decision frameworks.",
        "Anchor contentious debates to shared mission criteria to defuse personal friction.",
        ["Education", "Corporate", "Nonprofit"],
        micro_scenario={
            "triggerOption": "B",
            "complication": "After establishing criteria, the scores tie 50-50, and time to launch has narrowed to two weeks.",
            "followUpQuestion": "With a deadlock and ticking clock, what is your next leadership move?",
            "followUpOptions": [
                {"key": "A", "text": "Propose a hybrid pilot: launch the digital portal first, with a compact physical pop-up exhibit, establishing an unambiguous lead owner for each.", "score": 95, "trait": "pragmatic_synthesizer"},
                {"key": "B", "text": "Cancel the showcase entirely because consensus could not be reached.", "score": 30, "trait": "paralysis"},
                {"key": "C", "text": "Flip a coin to decide.", "score": 45, "trait": "arbitrary_gambler"}
            ]
        }
    ))

    # Q17: Foundation - Business / Business IQ
    questions.append(make_q(
        17, 1, "Business",
        "A startup team wants to add 15 complex features to an MVP (Minimum Viable Product) before launching, pushing their launch date back by 8 months.",
        "From a core business perspective, what advice is most critical?",
        [
            ("A", "Support the delay because a product must be completely feature-complete to avoid bad reviews.", {"business_iq": 45, "critical_thinking_iq": 45, "creativity_iq": 50, "problem_solving_iq": 45}, "high", "perfectionism_trap"),
            ("B", "Prioritize the core value hypothesis into a lean feature set, launch early to real users, and use actual customer usage data to guide subsequent releases.", {"business_iq": 95, "critical_thinking_iq": 90, "time_priority_iq": 90, "learning_agility_iq": 85}, "low", "lean_validation"),
            ("C", "Add 10 more features to ensure all competitor angles are also covered.", {"business_iq": 30, "time_priority_iq": 30, "critical_thinking_iq": 35, "problem_solving_iq": 30}, "high", "scope_bloat"),
            ("D", "Launch immediately today with whatever incomplete broken features currently exist.", {"business_iq": 50, "job_readiness_iq": 45, "time_priority_iq": 60, "critical_thinking_iq": 45}, "high", "reckless_release")
        ],
        {"business_iq": 45, "critical_thinking_iq": 25, "time_priority_iq": 20, "learning_agility_iq": 10},
        45,
        "Commercial success stems from rapid hypothesis validation in real market environments rather than isolated theoretical feature accumulation.",
        "Minimize cycle time to customer feedback; avoid speculative multi-month roadmaps unanchored to user behavior.",
        ["Startups", "IT", "Consulting", "Finance"]
    ))

    # Q18: Foundation - Creativity / Creativity IQ
    questions.append(make_q(
        18, 1, "Creativity",
        "Your team must organize a customer appreciation event on a budget that was abruptly cut by 70% due to company-wide austerity measures.",
        "How do you harness creative problem-solving?",
        [
            ("A", "Cancel the event entirely because an event with 30% budget will look cheap and embarrass the brand.", {"creativity_iq": 40, "problem_solving_iq": 40, "adaptability_iq": 45, "business_iq": 45}, "moderate", "resignation"),
            ("B", "Reimagine the format: replace an expensive banquet hall with an intimate, high-impact virtual masterclass with top industry thought-leaders and personalized digital gifts.", {"creativity_iq": 95, "problem_solving_iq": 90, "adaptability_iq": 95, "business_iq": 90}, "low", "inventive_pivot"),
            ("C", "Overspend the budget anyway and ask for retroactive forgiveness after the invoices arrive.", {"creativity_iq": 35, "ethics_judgment_iq": 30, "job_readiness_iq": 30, "business_iq": 35}, "high", "budgetary_insubordination"),
            ("D", "Keep the exact same banquet hall plan but cut food and drink portions down to almost nothing.", {"creativity_iq": 45, "marketing_iq": 45, "eq": 45, "problem_solving_iq": 40}, "high", "degraded_experience")
        ],
        {"creativity_iq": 45, "adaptability_iq": 25, "problem_solving_iq": 20, "business_iq": 10},
        45,
        "Creative leadership reframes budget constraints into format innovations rather than delivering degraded legacy experiences.",
        "When resources shrink, challenge the medium, not the mission.",
        ["Marketing", "Hospitality", "Consulting", "Retail"]
    ))

    # Q19: Foundation - Job Readiness / Job Readiness IQ
    questions.append(make_q(
        19, 1, "Workplace",
        "You are attending your first company town hall where senior executives invite questions from any employee. You have a burning question regarding career progression paths.",
        "What is the most professional conduct?",
        [
            ("A", "Grab the mic and passionately complain that freshers don't get promoted fast enough in your department.", {"job_readiness_iq": 35, "communication_iq": 40, "eq": 35, "promotion_readiness_iq": 35}, "high", "emotional_venting"),
            ("B", "Frame a structured, constructive question regarding company skill frameworks and upcoming capability programs that benefit the broader junior cohort.", {"job_readiness_iq": 95, "communication_iq": 95, "leadership_iq": 85, "promotion_readiness_iq": 90}, "low", "strategic_inquiry"),
            ("C", "Remain completely silent and avoid participating in any public forum throughout your tenure.", {"job_readiness_iq": 55, "communication_iq": 50, "leadership_iq": 45, "promotion_readiness_iq": 50}, "low", "invisible_retraction"),
            ("D", "Post an anonymous spicy critique in the internal chat room during the livestream.", {"job_readiness_iq": 30, "ethics_judgment_iq": 35, "eq": 30, "communication_iq": 35}, "high", "cynical_sniping")
        ],
        {"job_readiness_iq": 40, "communication_iq": 30, "promotion_readiness_iq": 15, "eq": 15},
        40,
        "High-visibility corporate interactions reflect your organizational maturity; frame personal aspirations within collective strategic growth.",
        "In all-hands forums, elevate personal questions into collective, forward-looking capability themes.",
        ["All"]
    ))

    # Q20: Foundation - Promotion Readiness / Strategic Maturity
    questions.append(make_q(
        20, 1, "Promotion",
        "You successfully finish all assigned tasks two hours ahead of schedule almost every day, but your manager hasn't noticed your extra capacity.",
        "What is the most constructive way to demonstrate promotion readiness?",
        [
            ("A", "Quietly browse social media or play games at your desk while pretending to be busy.", {"promotion_readiness_iq": 30, "job_readiness_iq": 35, "ethics_judgment_iq": 35, "business_iq": 30}, "high", "slacking"),
            ("B", "Proactively approach your lead, present the completed tasks, and propose taking on an internal tooling or documentation enhancement project during spare capacity.", {"promotion_readiness_iq": 95, "job_readiness_iq": 95, "leadership_iq": 90, "business_iq": 85}, "low", "proactive_value_creation"),
            ("C", "Demand an immediate salary increase on the grounds that you work twice as fast as your peers.", {"promotion_readiness_iq": 40, "eq": 40, "communication_iq": 45, "job_readiness_iq": 40}, "high", "entitled_demand"),
            ("D", "Slow your work pace down intentionally so every task stretches to fill the full eight hours.", {"promotion_readiness_iq": 35, "job_readiness_iq": 40, "learning_agility_iq": 35, "business_iq": 35}, "moderate", "artificial_drag")
        ],
        {"promotion_readiness_iq": 40, "job_readiness_iq": 30, "leadership_iq": 20, "business_iq": 10},
        40,
        "Promotion signals are forged by turning excess capacity into institutional leverage, process improvement, and cross-functional support.",
        "Do not conceal velocity; channel spare cycles into high-visibility, proactive organizational contributions.",
        ["All"]
    ))

    # =========================================================================
    # LEVEL 2: PROFESSIONAL (Q21 - Q40)
    # =========================================================================

    # Q21: Professional - Workplace / Cross-functional Alignment
    questions.append(make_q(
        21, 2, "Workplace",
        "The Marketing department promises clients a feature launch date for next month, but the Engineering team informs you that security audits require an extra six weeks.",
        "As the project coordinator, how do you resolve this standoff?",
        [
            ("A", "Side with Marketing and pressure Engineering to bypass optional penetration tests.", {"critical_thinking_iq": 40, "ethics_judgment_iq": 40, "leadership_iq": 45, "risk": "high"}, "high", "security_compromise"),
            ("B", "Bring both team leads together to analyze release scope: identify whether a secure 'phase one' subset can launch on time while the remaining features release post-audit.", {"problem_solving_iq": 95, "leadership_iq": 95, "communication_iq": 90, "business_iq": 90}, "low", "phased_compromise"),
            ("C", "Side with Engineering and let Marketing handle the client fallout on their own without communication assistance.", {"teamwork_iq": 50, "communication_iq": 55, "leadership_iq": 55, "eq": 50}, "moderate", "siloed_isolation"),
            ("D", "Draft a memo to the CEO claiming both departments are failing to cooperate.", {"communication_iq": 45, "leadership_iq": 40, "eq": 40, "job_readiness_iq": 45}, "high", "premature_escalation")
        ],
        {"leadership_iq": 35, "problem_solving_iq": 30, "communication_iq": 20, "business_iq": 15},
        45,
        "Professional cross-functional leadership seeks non-zero-sum solutions: explore phased modular releases to maintain customer momentum without violating security gates.",
        "Break binary deadlocks by dissecting monolithic milestones into phased deliverable tiers.",
        ["IT", "Marketing", "Consulting", "Finance"]
    ))

    # Q22: Professional - Communication / Executive Communication
    questions.append(make_q(
        22, 2, "Communication",
        "Your project is trending 2 weeks behind schedule. Your manager is known for having a short temper when hearing bad news.",
        "How and when do you deliver the progress update?",
        [
            ("A", "Conceal the delay until the official delivery day and hope your team works miracles over the final weekend.", {"communication_iq": 30, "job_readiness_iq": 30, "ethics_judgment_iq": 35, "time_priority_iq": 30}, "high", "crisis_concealment"),
            ("B", "Schedule an urgent 15-minute briefing now: state the 2-week projection clearly, present root causes, and offer two evaluated mitigation options with trade-offs.", {"communication_iq": 95, "eq": 90, "leadership_iq": 90, "time_priority_iq": 90}, "low", "solution_oriented_transparency"),
            ("C", "Send a casual Slack message on Friday night after your manager has left the office.", {"communication_iq": 45, "eq": 40, "job_readiness_iq": 45, "leadership_iq": 40}, "moderate", "conflict_avoidance"),
            ("D", "Ask a junior teammate to deliver the status report during the team sync.", {"communication_iq": 30, "eq": 30, "leadership_iq": 25, "ethics_judgment_iq": 35}, "high", "scapegoating")
        ],
        {"communication_iq": 40, "eq": 25, "leadership_iq": 20, "time_priority_iq": 15},
        40,
        "Bad news does not improve with age. Delivering bad news early accompanied by clear recovery paths is the hallmark of leadership maturity.",
        "Deliver bad news with immediate remedy options: Problem -> Root Cause -> 2 Evaluated Paths forward.",
        ["All"]
    ))

    # Q23: Professional - AI / Operational AI Integration
    questions.append(make_q(
        23, 2, "AI",
        "Your department is piloting an automated AI customer support responder. During weekend runs, the model gave contradictory refund guidelines to five enterprise accounts.",
        "What is your immediate technical and operational response?",
        [
            ("A", "Keep the AI running live because it handled hundreds of other inquiries successfully and 5 errors is within normal error tolerance.", {"aiq": 40, "business_iq": 40, "critical_thinking_iq": 45, "ethics_judgment_iq": 45}, "high", "reputational_risk"),
            ("B", "Pause automated responses for refund-related intents immediately, route them to human agents, and audit prompt system instructions and guardrail constraints.", {"aiq": 95, "critical_thinking_iq": 95, "business_iq": 90, "problem_solving_iq": 90}, "low", "guardrail_containment"),
            ("C", "Send an automated blast email blaming AI beta testing for all errors.", {"communication_iq": 40, "marketing_iq": 40, "eq": 45, "business_iq": 40}, "moderate", "public_deflection"),
            ("D", "Permanently scrap the entire AI automation initiative across the enterprise.", {"aiq": 45, "adaptability_iq": 40, "problem_solving_iq": 45, "business_iq": 45}, "moderate", "overreaction")
        ],
        {"aiq": 40, "critical_thinking_iq": 30, "business_iq": 20, "problem_solving_iq": 10},
        45,
        "Responsible AI operations require instant circuit breakers on high-risk intents (e.g. monetary commitments) while preserving human fallback channels.",
        "Implement guardrails and human verification loops before scaling autonomous LLM actions to financial touchpoints.",
        ["IT", "Finance", "Retail", "Customer Service"]
    ))

    # Q24: Professional - Critical Thinking / Data Interpretation
    questions.append(make_q(
        24, 2, "Critical Thinking",
        "A vendor presents an analytics dashboard showing that their onboarding software increased employee retention by 40% across their pilot cohort of 20 hand-picked volunteer employees.",
        "What methodological flaw should you challenge before signing an enterprise contract?",
        [
            ("A", "Accept the metric because a 40% gain clearly justifies the software licensing cost.", {"critical_thinking_iq": 35, "business_iq": 40, "iq": 45, "problem_solving_iq": 40}, "high", "credulous_acceptance"),
            ("B", "Highlight selection bias: hand-picked volunteers are inherently more motivated than the broader employee population, requiring a randomized control trial.", {"critical_thinking_iq": 98, "iq": 95, "business_iq": 90, "problem_solving_iq": 85}, "low", "selection_bias_critique"),
            ("C", "Reject the vendor solely because you personally dislike automated onboarding tools.", {"critical_thinking_iq": 40, "eq": 40, "business_iq": 45, "communication_iq": 45}, "moderate", "subjective_bias"),
            ("D", "Ask them to increase the font size of the chart to verify the numbers.", {"critical_thinking_iq": 30, "iq": 30, "job_readiness_iq": 40, "problem_solving_iq": 35}, "high", "superficial_focus")
        ],
        {"critical_thinking_iq": 45, "business_iq": 25, "iq": 20, "problem_solving_iq": 10},
        45,
        "Rigorous professional judgment interrogates sampling methodology and selection bias before committing enterprise capital.",
        "Scrutinize pilot sample selection: voluntary self-selected cohorts rarely mirror representative organizational realities.",
        ["Consulting", "HR", "Finance", "Corporate"]
    ))

    # Q25: Professional - Leadership / Coaching & Performance (with Micro-Scenario)
    questions.append(make_q(
        25, 2, "Leadership",
        "A talented team member with deep domain knowledge has recently started turning in incomplete work and appears disengaged during planning sessions.",
        "What is your leadership approach to re-engaging them?",
        [
            ("A", "Place them on a formal performance improvement plan (PIP) without prior discussion.", {"leadership_iq": 45, "eq": 40, "communication_iq": 50, "job_readiness_iq": 50}, "high", "bureaucratic_hammer"),
            ("B", "Conduct a private, open-ended 1-on-1: share specific observations about their work pattern, listen for underlying blockers or career plateau fatigue, and co-design a renewal plan.", {"leadership_iq": 95, "eq": 95, "communication_iq": 90, "promotion_readiness_iq": 90}, "low", "supportive_coaching"),
            ("C", "Reassign their complex work to other peers silently so deadlines are met.", {"leadership_iq": 50, "eq": 50, "teamwork_iq": 55, "time_priority_iq": 55}, "moderate", "silent_sidelining"),
            ("D", "Wait another three months to see if their motivation naturally returns.", {"leadership_iq": 40, "time_priority_iq": 40, "job_readiness_iq": 45, "eq": 45}, "high", "neglectful_delay")
        ],
        {"leadership_iq": 40, "eq": 30, "communication_iq": 20, "promotion_readiness_iq": 10},
        45,
        "True leadership addresses disengagement early through empathetic curiosity, seeking to understand whether burnout, ambiguity, or skill mismatch is at play.",
        "Treat sudden disengagement as a diagnostic signal; address root causes before escalating to disciplinary protocols.",
        ["All"],
        micro_scenario={
            "triggerOption": "B",
            "complication": "During the discussion, the team member reveals they feel their career has stalled because their daily operational tasks leave no time to learn modern cloud architecture.",
            "followUpQuestion": "How do you strategically address their career stagnation while maintaining team deliverables?",
            "followUpOptions": [
                {"key": "A", "text": "Carve out 10% protected learning time tied to automating their routine tasks, with an agreement to lead an upcoming cloud migration pilot.", "score": 95, "trait": "empowering_strategist"},
                {"key": "B", "text": "Tell them career growth must happen strictly outside office hours on their personal time.", "score": 45, "trait": "unsympathetic_gatekeeper"},
                {"key": "C", "text": "Promote them immediately without any change in responsibilities.", "score": 40, "trait": "unmerited_appeasement"}
            ]
        }
    ))

    # Q26: Professional - Programming / Code Review & Quality
    questions.append(make_q(
        26, 2, "Programming",
        "During a code review for an urgent production hotfix, you notice that a senior developer introduced a hardcoded credentials secret and skipped unit tests to hit a 6:00 PM release.",
        "How do you handle this critical architectural risk?",
        [
            ("A", "Approve the review silently since the author is more senior and understands the urgency.", {"ethics_judgment_iq": 30, "programming_iq": 35, "job_readiness_iq": 35, "critical_thinking_iq": 35}, "high", "deferential_negligence"),
            ("B", "Block the release politely: clearly cite the security compliance violation, suggest extracting the secret to environment variables, and offer to help write the minimal test harness.", {"ethics_judgment_iq": 95, "programming_iq": 95, "communication_iq": 90, "job_readiness_iq": 90}, "low", "principled_safeguard"),
            ("C", "Post a screenshot of the secret on an open public Slack channel to embarrass the developer.", {"communication_iq": 30, "eq": 25, "teamwork_iq": 25, "job_readiness_iq": 35}, "high", "toxic_confrontation"),
            ("D", "Approve it now, but add a calendar reminder to fix it sometime next quarter.", {"programming_iq": 50, "ethics_judgment_iq": 45, "time_priority_iq": 45, "critical_thinking_iq": 45}, "high", "technical_debt_recklessness")
        ],
        {"ethics_judgment_iq": 35, "programming_iq": 35, "communication_iq": 20, "job_readiness_iq": 10},
        45,
        "Security and architectural integrity must never be traded off for release velocity, regardless of seniority.",
        "Stand firm on non-negotiable security standards while offering collaborative assistance to clear the bottleneck.",
        ["IT", "Finance", "Cybersecurity"]
    ))

    # Q27: Professional - Business / Financial Trade-offs
    questions.append(make_q(
        27, 2, "Business",
        "Your department has $50,000 remaining in the annual budget. The team wants to use it for a luxury team retreat, while customer support is severely under-tooled and causing customer churn.",
        "What recommendation reflects the soundest business judgment?",
        [
            ("A", "Spend the entire $50,000 on the luxury retreat because team morale is all that matters.", {"business_iq": 40, "critical_thinking_iq": 40, "time_priority_iq": 45, "leadership_iq": 45}, "high", "fiduciary_myopia"),
            ("B", "Allocate $35,000 to modernize support tooling to curb churn, and dedicate $15,000 to a focused, meaningful regional team celebration.", {"business_iq": 95, "critical_thinking_iq": 90, "leadership_iq": 90, "eq": 85}, "low", "balanced_capital_allocation"),
            ("C", "Return the entire $50,000 unspent to corporate finance so management thinks you save money.", {"business_iq": 60, "leadership_iq": 50, "teamwork_iq": 45, "job_readiness_iq": 55}, "moderate", "budget_surrender"),
            ("D", "Hide the surplus in miscellaneous expenses until next fiscal year.", {"business_iq": 30, "ethics_judgment_iq": 25, "job_readiness_iq": 30, "critical_thinking_iq": 35}, "high", "unethical_accounting")
        ],
        {"business_iq": 45, "leadership_iq": 25, "critical_thinking_iq": 20, "eq": 10},
        45,
        "Strategic business orientation balances top-line retention drivers with human team engagement through balanced capital allocation.",
        "Align departmental spending with customer retention and employee engagement without excessive binary extremes.",
        ["Corporate", "Finance", "Operations", "Consulting"]
    ))

    # Q28: Professional - Marketing / Brand Positioning (with Micro-Scenario)
    questions.append(make_q(
        28, 2, "Marketing",
        "A competitor launches a viral advertising campaign humorously parodying your company's product reliability, generating millions of views and trending hashtags.",
        "What is your strategic marketing response?",
        [
            ("A", "File an immediate defamation lawsuit and issue threatening cease-and-desist press statements.", {"marketing_iq": 40, "communication_iq": 45, "business_iq": 40, "eq": 40}, "high", "streisand_effect"),
            ("B", "Evaluate audience sentiment data first: if playful, craft a witty, confident, brand-affirming rebuttal showcasing real customer testimonials and audited uptime metrics.", {"marketing_iq": 95, "communication_iq": 90, "critical_thinking_iq": 90, "creativity_iq": 90}, "low", "measured_brand_counter"),
            ("C", "Completely ignore it and pretend the viral campaign doesn't exist.", {"marketing_iq": 55, "communication_iq": 50, "critical_thinking_iq": 55, "adaptability_iq": 50}, "moderate", "passive_detachment"),
            ("D", "Launch an aggressive smear campaign attacking the personal life of the competitor's CEO.", {"marketing_iq": 25, "ethics_judgment_iq": 20, "communication_iq": 25, "eq": 25}, "high", "brand_suicide")
        ],
        {"marketing_iq": 40, "communication_iq": 25, "critical_thinking_iq": 20, "creativity_iq": 15},
        45,
        "Brand defense in modern media requires emotional poise: analyze sentiment trends and leverage high-visibility moments to reinforce authentic brand strengths.",
        "Never react defensively to competitive satire; redirect viral attention toward your verified value propositions.",
        ["Marketing", "Media", "Startups", "Retail"],
        micro_scenario={
            "triggerOption": "B",
            "complication": "Your witty response gains strong traction, but an industry influencer calls out a single legacy outage from two years ago in the comment section.",
            "followUpQuestion": "How do you address the influencer's pointed call-out?",
            "followUpOptions": [
                {"key": "A", "text": "Own the historical incident candidly, link to the published post-mortem report, and highlight the architectural redundancy investments built since.", "score": 95, "trait": "radically_transparent"},
                {"key": "B", "text": "Block the influencer immediately and delete their comment.", "score": 30, "trait": "censorship_backfire"},
                {"key": "C", "text": "Deny that the outage ever occurred.", "score": 25, "trait": "blatant_untruth"}
            ]
        }
    ))

    # Q29: Professional - Time & Priority / Managing Scope Creep
    questions.append(make_q(
        29, 2, "Time & Priority",
        "A key corporate client sends a series of 'small quick change requests' every other day, which individually take 2 hours but collectively have expanded project scope by 35%.",
        "How do you regain control over the project timeline?",
        [
            ("A", "Accept all requests without comment and make your team work unpaid weekends to absorb the overhead.", {"time_priority_iq": 35, "teamwork_iq": 40, "job_readiness_iq": 45, "business_iq": 40}, "high", "burnout_absorption"),
            ("B", "Compile a consolidated change-impact matrix: show the cumulative timeline and budget variance, and establish a formal Change Request sign-off process.", {"time_priority_iq": 95, "business_iq": 95, "communication_iq": 90, "leadership_iq": 85}, "low", "scope_governance"),
            ("C", "Abruptly stop replying to the client's emails.", {"communication_iq": 30, "eq": 30, "job_readiness_iq": 35, "sales_iq": 30}, "high", "unprofessional_ghosting"),
            ("D", "Complain to your team members in private while continuing to say yes to the client.", {"leadership_iq": 40, "eq": 40, "communication_iq": 40, "job_readiness_iq": 40}, "moderate", "passive_resentment")
        ],
        {"time_priority_iq": 40, "business_iq": 30, "communication_iq": 20, "leadership_iq": 10},
        45,
        "Scope creep is neutralized by transparent data: visualize cumulative impact and introduce structured change controls with cost/schedule trade-offs.",
        "Educate clients on trade-offs through systematic impact logs rather than emotional pushback.",
        ["Consulting", "IT", "Operations", "Finance"]
    ))

    # Q30: Professional - Adaptability / Market Disruption
    questions.append(make_q(
        30, 2, "Adaptability",
        "A sudden economic downturn causes three prospective enterprise deals to freeze, placing your team's quarterly revenue target in severe jeopardy.",
        "What is your immediate adaptability strategy?",
        [
            ("A", "Wait until the next quarter to see if macroeconomic conditions naturally improve.", {"adaptability_iq": 40, "business_iq": 40, "problem_solving_iq": 45, "sales_iq": 40}, "moderate", "paralyzed_inertia"),
            ("B", "Pivot focus toward existing account retention, upsell modular high-ROI add-ons, and package smaller pilot contracts with shorter evaluation cycles.", {"adaptability_iq": 95, "business_iq": 95, "sales_iq": 90, "problem_solving_iq": 90}, "low", "counter_cyclical_pivot"),
            ("C", "Blame the sales reps publicly for not closing deals faster before the downturn.", {"eq": 30, "leadership_iq": 30, "teamwork_iq": 30, "communication_iq": 35}, "high", "punitive_blame"),
            ("D", "Slash list prices by 70% across the board without margin analysis.", {"business_iq": 40, "critical_thinking_iq": 40, "sales_iq": 45, "problem_solving_iq": 40}, "high", "panic_discounting")
        ],
        {"adaptability_iq": 40, "business_iq": 30, "sales_iq": 20, "problem_solving_iq": 10},
        45,
        "Commercial resilience under macroeconomic headwind requires pivoting from large capital-intensive deals to rapid-value, lower-friction retention and expansion offerings.",
        "When macro tailwinds stall, fortify core accounts and lower deal friction with modular entry options.",
        ["Sales", "Business", "Startups", "Finance"]
    ))

    # Q31: Professional - Ethics / Intellectual Property & Integrity
    questions.append(make_q(
        31, 2, "Ethical",
        "A newly hired colleague brings proprietary client databases and presentation decks from their prior employer, suggesting your team use them to prospect new leads.",
        "What is your ethical and professional duty?",
        [
            ("A", "Use the databases immediately since gaining a competitive edge is the purpose of hiring industry veterans.", {"ethics_judgment_iq": 20, "job_readiness_iq": 25, "critical_thinking_iq": 30, "business_iq": 30}, "high", "ip_theft_complicity"),
            ("B", "Decline to touch or use the material, remind the colleague of non-disclosure and trade secret legal obligations, and escalate the matter to Legal/Compliance.", {"ethics_judgment_iq": 98, "job_readiness_iq": 95, "leadership_iq": 90, "critical_thinking_iq": 85}, "low", "compliance_fortress"),
            ("C", "Browse the slides out of personal curiosity but don't share them with clients.", {"ethics_judgment_iq": 45, "job_readiness_iq": 45, "eq": 50, "critical_thinking_iq": 45}, "moderate", "passive_compromise"),
            ("D", "Encourage them to rebrand the slides with your company logo to disguise their origin.", {"ethics_judgment_iq": 15, "job_readiness_iq": 20, "business_iq": 20, "critical_thinking_iq": 25}, "high", "willful_fraud")
        ],
        {"ethics_judgment_iq": 50, "job_readiness_iq": 25, "leadership_iq": 15, "critical_thinking_iq": 10},
        40,
        "Intellectual property integrity is a strict legal and ethical boundary; utilizing a competitor's confidential data exposes the company to severe litigation.",
        "Protect organizational immunity by rejecting contaminated IP immediately and engaging legal counsel.",
        ["All"]
    ))

    # Q32: Professional - Sales / Objection Handling & Value
    questions.append(make_q(
        32, 2, "Sales",
        "A prospective B2B buyer remarks: 'Your product looks good, but my team is already overwhelmed and we simply do not have the bandwidth to learn another tool right now.'",
        "How do you address this adoption-friction objection?",
        [
            ("A", "Tell them that if they don't modernize now, their business will become obsolete.", {"sales_iq": 45, "communication_iq": 45, "eq": 40, "business_iq": 45}, "high", "fear_mongering"),
            ("B", "Validate their bandwidth concern, then demonstrate how your team provides turnkey migration, automated data import, and a 15-minute onboarding curve that saves 6 hours/week immediately.", {"sales_iq": 95, "communication_iq": 95, "eq": 90, "business_iq": 85}, "low", "friction_removal"),
            ("C", "Offer to delay the contract by two years until they have more time.", {"sales_iq": 40, "business_iq": 40, "time_priority_iq": 45, "problem_solving_iq": 40}, "moderate", "premature_surrender"),
            ("D", "Insist that learning the tool is actually extremely easy and they shouldn't complain.", {"sales_iq": 35, "communication_iq": 40, "eq": 30, "job_readiness_iq": 40}, "high", "dismissive_invalidation")
        ],
        {"sales_iq": 40, "communication_iq": 30, "eq": 20, "business_iq": 10},
        45,
        "Elite objection handling validates human friction (switching costs and fatigue) and actively de-risks implementation effort.",
        "Do not deny the customer's transition pain; provide concrete friction-mitigation structures.",
        ["Sales", "Consulting", "Tech", "Healthcare"]
    ))

    # Q33: Professional - Interview / Candidate Assessment
    questions.append(make_q(
        33, 2, "Interview",
        "You are interviewing a candidate who has flawless technical answers memorized from popular online cheat sheets, but stumbles completely when asked to explain how they handled an unexpected failure in real life.",
        "How do you evaluate their potential?",
        [
            ("A", "Give them a top rating because their technical memorization was 100% accurate.", {"interview_iq": 40, "critical_thinking_iq": 40, "job_readiness_iq": 45, "iq": 50}, "high", "rote_bias"),
            ("B", "Probe deeper with adaptive behavioral micro-scenarios: ask them to reason through an ambiguous, unscripted edge case to assess problem-solving adaptability over memorization.", {"interview_iq": 95, "critical_thinking_iq": 95, "problem_solving_iq": 90, "eq": 85}, "low", "depth_evaluation"),
            ("C", "Immediately terminate the interview and tell them they are unprepared.", {"interview_iq": 45, "eq": 35, "communication_iq": 40, "job_readiness_iq": 45}, "high", "premature_abrasiveness"),
            ("D", "Ask them to recite more textbook definitions to confirm their memory.", {"interview_iq": 35, "critical_thinking_iq": 35, "learning_agility_iq": 35, "iq": 40}, "moderate", "surface_fixation")
        ],
        {"interview_iq": 45, "critical_thinking_iq": 30, "eq": 15, "problem_solving_iq": 10},
        45,
        "Authentic capability shines in unscripted navigation of failure, not memorized theoretical regurgitation.",
        "Shift candidate evaluation from static recall to interactive problem decomposition under novel constraints.",
        ["HR", "IT", "Consulting", "Management"]
    ))

    # Q34: Professional - Promotion / Leadership Influence
    questions.append(make_q(
        34, 2, "Promotion",
        "You are technically the top individual producer on your team, but in your mid-year review your manager notes: 'Your individual output is stellar, but your organizational influence and mentorship footprint remain limited.'",
        "What strategic shift elevates your readiness for promotion?",
        [
            ("A", "Work even longer hours to double your individual code or sales output.", {"promotion_readiness_iq": 45, "leadership_iq": 40, "business_iq": 45, "critical_thinking_iq": 45}, "moderate", "linear_doubling"),
            ("B", "Shift focus from purely personal production to institutional multiplier: host weekly technical office hours, author re-usable process blueprints, and actively mentor two junior colleagues.", {"promotion_readiness_iq": 98, "leadership_iq": 98, "business_iq": 90, "teamwork_iq": 90}, "low", "multiplier_leadership"),
            ("C", "Argue that mentorship is the manager's sole responsibility, not yours.", {"promotion_readiness_iq": 35, "eq": 30, "communication_iq": 35, "job_readiness_iq": 40}, "high", "role_rigidity"),
            ("D", "Apply for jobs at competitor firms where managers supposedly only care about individual stats.", {"promotion_readiness_iq": 40, "eq": 40, "adaptability_iq": 45, "job_readiness_iq": 40}, "moderate", "evasion")
        ],
        {"promotion_readiness_iq": 45, "leadership_iq": 35, "business_iq": 10, "teamwork_iq": 10},
        45,
        "Promotion from individual contributor to senior leadership requires evolving from an individual performer into a team force multiplier.",
        "Senior promotions measure how much better everyone else performs because of your systemic enablement.",
        ["All"]
    ))

    # Q35: Professional - Crisis / Operational Incident Management (with Micro-Scenario)
    questions.append(make_q(
        35, 2, "Crisis",
        "At 11:00 AM on a high-volume trading or sales day, a critical database synchronization service stalls, causing transaction backlogs across 2,000 pending orders.",
        "What is the first protocol you initiate as incident manager?",
        [
            ("A", "Start messaging team members to find out who made the last commit and assign blame.", {"problem_solving_iq": 35, "leadership_iq": 35, "eq": 35, "crisis_iq": 30}, "high", "witch_hunt"),
            ("B", "Establish a dedicated incident war-room, assign an incident commander and communications lead, isolate incoming traffic to prevent queue saturation, and begin telemetry analysis.", {"problem_solving_iq": 95, "leadership_iq": 95, "time_priority_iq": 95, "crisis_iq": 95}, "low", "structured_incident_protocol"),
            ("C", "Shut down all servers instantly without alerting clients or customer support.", {"problem_solving_iq": 45, "business_iq": 40, "communication_iq": 40, "risk": "high"}, "high", "reckless_shutdown"),
            ("D", "Post a tweet saying the company has been attacked by mysterious international hackers.", {"ethics_judgment_iq": 25, "communication_iq": 25, "business_iq": 25, "risk": "high"}, "high", "sensationalist_fabrication")
        ],
        {"problem_solving_iq": 35, "leadership_iq": 30, "time_priority_iq": 20, "communication_iq": 15},
        45,
        "Incident management demands disciplined process: isolate blast radius, assign distinct operational and communication roles, and defer root-cause finger-pointing until stabilization.",
        "Under operational fire, maintain strict role segregation: technical triage, customer comms, executive updates.",
        ["IT", "Finance", "Logistics", "Operations"],
        micro_scenario={
            "triggerOption": "B",
            "complication": "While diagnosing the backlog, the Vice President of Sales calls your cell phone demanding you restore the service immediately regardless of data corruption risks.",
            "followUpQuestion": "How do you handle the VP's high-pressure demand?",
            "followUpOptions": [
                {"key": "A", "text": "Calmly explain that skipping integrity checks could corrupt 2,000 existing transactions permanently, provide a firm 20-minute checkpoint, and ask the comms lead to send the executive status bulletin.", "score": 95, "trait": "composed_integrity"},
                {"key": "B", "text": "Capitulate to the VP's pressure and force restart the database immediately.", "score": 35, "trait": "pressure_collapse"},
                {"key": "C", "text": "Hang up on the VP abruptly.", "score": 30, "trait": "insubordinate_hostility"}
            ]
        }
    ))

    # Q36: Professional - Learning Agility / Upskilling & Disruption
    questions.append(make_q(
        36, 2, "Learning",
        "Generative AI tools emerge that automate 60% of the manual reporting and synthesis tasks that previously occupied the majority of your weekly work hours.",
        "How do you position your role for the future?",
        [
            ("A", "Ban the tools in your department and advocate for strictly manual spreadsheet compilation.", {"learning_agility_iq": 35, "adaptability_iq": 35, "aiq": 30, "job_readiness_iq": 40}, "high", "luddite_resistance"),
            ("B", "Embrace the automation tools to execute routine synthesis in minutes, while redirecting your freed time toward strategic advisory, anomaly detection, and stakeholder relationship building.", {"learning_agility_iq": 98, "aiq": 95, "adaptability_iq": 95, "business_iq": 90}, "low", "value_chain_elevation"),
            ("C", "Keep using the tools secretly, finish your work in 1 hour, and sleep for the remaining 7 hours of the workday.", {"ethics_judgment_iq": 35, "job_readiness_iq": 35, "promotion_readiness_iq": 35, "learning_agility_iq": 45}, "high", "deceptive_slacking"),
            ("D", "Assume your career is finished and begin searching for an entirely unrelated blue-collar trade.", {"learning_agility_iq": 45, "adaptability_iq": 45, "eq": 40, "critical_thinking_iq": 45}, "moderate", "fatalistic_surrender")
        ],
        {"learning_agility_iq": 35, "aiq": 35, "adaptability_iq": 20, "business_iq": 10},
        45,
        "Technological disruption automates mechanical execution; elite professionals shift up the cognitive stack toward judgment, orchestration, and relationship capital.",
        "Automate the commodity layer of your tasks so you can dominate the strategic advisory layer.",
        ["All"]
    ))

    # Q37: Professional - Teamwork / Healthy Disagreement
    questions.append(make_q(
        37, 2, "Teamwork",
        "During a team sprint retro, everyone nods in silent agreement to a proposed architecture plan that you know from prior benchmarks will fail under peak holiday traffic.",
        "How do you voice your objection constructively?",
        [
            ("A", "Keep quiet to avoid disrupting the positive team consensus, since group harmony is paramount.", {"teamwork_iq": 45, "critical_thinking_iq": 40, "communication_iq": 45, "job_readiness_iq": 45}, "moderate", "groupthink_compliance"),
            ("B", "Acknowledge the elegance of the proposed plan, then share the specific load benchmark data, framing it as an edge-case stress test: 'Let us see how this holds at 50,000 concurrent requests.'", {"teamwork_iq": 95, "critical_thinking_iq": 95, "communication_iq": 95, "eq": 90}, "low", "data_grounded_inquiry"),
            ("C", "Tell the team lead in front of everyone that the architecture shows total technical incompetence.", {"communication_iq": 30, "eq": 25, "teamwork_iq": 30, "leadership_iq": 35}, "high", "abrasive_attack"),
            ("D", "Wait until the holiday traffic crash occurs so you can tell everyone 'I told you so.'", {"teamwork_iq": 25, "eq": 25, "ethics_judgment_iq": 30, "leadership_iq": 30}, "high", "sabotage_satisfaction")
        ],
        {"teamwork_iq": 35, "critical_thinking_iq": 35, "communication_iq": 20, "eq": 10},
        40,
        "Psychological safety is not harmony; it is the freedom to challenge flawed assumptions constructively with empirical evidence.",
        "Dissent with data and curiosity: test the boundary condition rather than attacking the proposal author.",
        ["IT", "Engineering", "Consulting", "Finance"]
    ))

    # Q38: Professional - Creativity / Innovative Optimization
    questions.append(make_q(
        38, 2, "Creativity",
        "A legacy manufacturing or service process requires employees to manually cross-reference paper invoices with digital logs, causing a perpetual 3-day backlog.",
        "What creative optimization methodology do you introduce?",
        [
            ("A", "Demand that employees work overtime each evening until the paper backlog clears.", {"creativity_iq": 35, "problem_solving_iq": 40, "leadership_iq": 40, "time_priority_iq": 40}, "moderate", "brute_force_exhaustion"),
            ("B", "Map the complete step-by-step value stream, identify the redundant manual checkpoints, and prototype an OCR (Optical Character Recognition) pipeline to automate reconciliation.", {"creativity_iq": 95, "problem_solving_iq": 95, "business_iq": 90, "learning_agility_iq": 90}, "low", "process_innovation"),
            ("C", "Stop checking paper invoices altogether and hope no financial discrepancies occur.", {"ethics_judgment_iq": 30, "risk": "high", "critical_thinking_iq": 35, "job_readiness_iq": 35}, "high", "reckless_abandonment"),
            ("D", "Hire 10 additional temporary interns to handle the paper filing.", {"business_iq": 50, "creativity_iq": 45, "problem_solving_iq": 50, "time_priority_iq": 55}, "moderate", "headcount_bandaid")
        ],
        {"creativity_iq": 40, "problem_solving_iq": 30, "business_iq": 20, "learning_agility_iq": 10},
        45,
        "True process innovation rethinks the fundamental workflow rather than adding more human toil to broken manual pipes.",
        "Map the value stream first; eliminate non-value checkpoints before automating what remains.",
        ["Manufacturing", "Operations", "Logistics", "Healthcare"]
    ))

    # Q39: Professional - Job Readiness / Workplace Boundary & Well-being
    questions.append(make_q(
        39, 2, "Workplace",
        "A manager frequently sends non-urgent work-related messages on messaging apps at 11:30 PM on weekend nights, creating chronic anxiety among the team.",
        "How do you professionally address this pattern?",
        [
            ("A", "Reply immediately at midnight to prove your absolute devotion to the job.", {"job_readiness_iq": 50, "time_priority_iq": 45, "eq": 50, "leadership_iq": 45}, "moderate", "anxiety_enabling"),
            ("B", "Set clear notification schedules, and during your regular 1-on-1, initiate a calm discussion: 'I want to ensure critical emergencies are never missed—what criteria distinguish a true off-hours emergency from items for Monday morning?'", {"job_readiness_iq": 95, "communication_iq": 95, "eq": 90, "time_priority_iq": 90}, "low", "boundary_negotiation"),
            ("C", "Block your manager's phone number without saying anything.", {"communication_iq": 35, "job_readiness_iq": 35, "eq": 35, "leadership_iq": 35}, "high", "passive_aggressive_block"),
            ("D", "Send angry messages back in all capital letters demanding they respect labor laws.", {"communication_iq": 30, "eq": 30, "job_readiness_iq": 30, "leadership_iq": 30}, "high", "volatile_escalation")
        ],
        {"job_readiness_iq": 35, "communication_iq": 35, "eq": 15, "time_priority_iq": 15},
        45,
        "Professional boundaries are forged through collaborative definition of emergency thresholds rather than silent resentment or abrupt confrontation.",
        "Clarify emergency protocols explicitly to decouple routine off-hours brain-dumps from urgent response requirements.",
        ["All"]
    ))

    # Q40: Professional - Interview / Situational Competency
    questions.append(make_q(
        40, 2, "Interview",
        "When interviewing for a senior role, the hiring manager asks: 'Tell me about a time you led a strategic initiative that completely failed.'",
        "What narrative structure demonstrates executive maturity?",
        [
            ("A", "Claim that you have never failed because your strategic preparation is always 100% thorough.", {"interview_iq": 35, "eq": 30, "learning_agility_iq": 30, "critical_thinking_iq": 35}, "high", "fabricated_perfection"),
            ("B", "Structure the narrative around accountability: describe the strategic premise, the unexpected failure point, the immediate containment actions, and the concrete institutional learnings adopted since.", {"interview_iq": 98, "learning_agility_iq": 95, "leadership_iq": 95, "eq": 90}, "low", "accountable_postmortem"),
            ("C", "Describe a failure, but attribute all fault entirely to incompetent junior team members or dishonest suppliers.", {"interview_iq": 30, "eq": 25, "leadership_iq": 25, "teamwork_iq": 25}, "high", "externalized_blame"),
            ("D", "Pick a fake flaw such as 'My failure was caring too much about work and delivering 3 days too early.'", {"interview_iq": 40, "communication_iq": 40, "eq": 35, "job_readiness_iq": 40}, "high", "cliché_humblebrag")
        ],
        {"interview_iq": 40, "leadership_iq": 25, "learning_agility_iq": 20, "eq": 15},
        45,
        "Authentic executive presence is proven by ownership of failure and the rigor of subsequent institutional learning.",
        "Own the failure directly; showcase diagnostic humility and how the experience forged sharper strategic reflexes.",
        ["All"]
    ))

    return questions

if __name__ == "__main__":
    qs = get_level1_and_level2()
    print(f"Loaded {len(qs)} questions for Level 1 and Level 2")
